[package]
name = "uind"
version = "0.1.0"
authors = ["Kai Ma <ksqsf@mail.ustc.edu.cn>"]
edition = "2018"

[dependencies]
tokio = "0.1.13"
failure = "0.1.3"
futures = "0.1.25"
bytes = "0.4.11"
env_logger = "0.6.0"
log = "0.4.6"
ttl_cache = "0.5.1"
